//
//  KotlinSwift2KotlinGenerator.swift
//  swift-java
//
//  Created by Ilya Plisko on 16.02.26.
//
import SwiftJavaConfigurationShared
import SwiftSyntax
import SwiftSyntaxBuilder
import Foundation

package class KotlinSwift2KotlinGenerator /* : Swift2JavaGenerator? or new protocol */ {
  let log: Logger
  let analysis: AnalysisResult
  let swiftModuleName: String
  let kotlinPackage: String
  let kotlinOutputDirectory: String

  package init(config: Configuration, translator: Swift2JavaTranslator,
               kotlinPackage: String, kotlinOutputDirectory: String) {
    self.log = Logger(label: "kotlin-generator", logLevel: translator.log.logLevel)
    self.analysis = translator.result               // same as FFM generator
    self.swiftModuleName = translator.swiftModuleName
    self.kotlinPackage = kotlinPackage
    self.kotlinOutputDirectory = kotlinOutputDirectory
  }

  func generate() throws {
    var printer = CodePrinter()
    try writeExportedKotlinSources(printer: &printer)
  }

  package func writeExportedKotlinSources(printer: inout CodePrinter) throws {
    let filename = "\(swiftModuleName).kt"
    printKotlinModuleFile(&printer)
    _ = try printer.writeContents(
      outputDirectory: kotlinOutputDirectory,
      javaPackagePath: kotlinPackage.replacingOccurrences(of: ".", with: "/"), // reuse path mechanism
      filename: filename
    )
  }

  func printKotlinModuleFile(_ printer: inout CodePrinter) {
    printer.print("// Generated by jextract-swift (kotlin-jvm mode)")
    printer.print("// Swift module: \(swiftModuleName)")
    printer.print("// Delegates to Java FFM bindings\n")
    printer.print("package \(kotlinPackage)\n")

    for decl in analysis.importedGlobalFuncs {
      printTopLevelKotlinFunction(&printer, decl)
      printer.print("")
    }
  }
  
  func printTopLevelKotlinFunction(_ printer: inout CodePrinter, _ decl: ImportedFunc) {
    // Only top-level functions: skip members/initializers/accessors/etc.
    guard decl.apiKind == .function else {
      printer.print("// Skipped \(decl.displayName): apiKind=\(decl.apiKind)")
      return
    }
    guard decl.hasParent == false else {
      printer.print("// Skipped \(decl.displayName): not a top-level function (has parent)")
      return
    }
    guard decl.isAsync == false else {
      printer.print("// Skipped \(decl.displayName): async not supported in kotlin-jvm stub mode")
      return
    }

    // Map Swift known types -> Kotlin primitives subset
    func swiftTypeToKotlin(_ t: SwiftType) -> String? {
      // Prefer semantic known-type mapping if available
      if let known = t.asNominalTypeDeclaration?.knownTypeKind {
        switch known {
        case .int:
          return "Long"
        case .int32:
          return "Int"
        case .bool:
          return "Boolean"
        case .double:
          return "Double"
        case .string:
          return "String"
        case .void:
          return "Unit"
        default:
          break
        }
      }

      // Fallback to simple textual matching (covers cases where knownTypeKind is absent)
      let s = String(describing: t)
      switch s {
      case "Int", "Swift.Int":
        return "Long"
      case "Int32", "Swift.Int32":
        return "Int"
      case "Bool", "Swift.Bool":
        return "Boolean"
      case "Double", "Swift.Double":
        return "Double"
      case "String", "Swift.String":
        return "String"
      case "Void", "Swift.Void", "()":
        return "Unit"
      default:
        return nil
      }
    }

    // Render parameters (primitive-only)
    var renderedParams: [String] = []
    renderedParams.reserveCapacity(decl.functionSignature.parameters.count)

    for (i, p) in decl.functionSignature.parameters.enumerated() {
      guard let ktTy = swiftTypeToKotlin(p.type) else {
        printer.print("// Skipped \(decl.displayName): unsupported param type '\(p.type)'")
        return
      }

      // Parameter naming:
      // - use `p.parameterName` if exists/non-empty
      // - otherwise synthesize p0, p1...
      var paramName = (p.parameterName?.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines) ?? "")
      if paramName.isEmpty || paramName == "_" {
        paramName = "p\(i)"
      }

      // Avoid Kotlin keyword collisions (minimal set; extend as needed)
      let kotlinKeywords: Set<String> = [
        "object","class","fun","val","var","when","is","in",
        "as","try","catch","finally","null","true","false"
      ]
      if kotlinKeywords.contains(paramName) {
        paramName = "`\(paramName)`"
      }

      renderedParams.append("\(paramName): \(ktTy)")
    }

    // Return type (primitive-only, no String returns - FFM doesn't support them yet)
    guard let ktReturn = swiftTypeToKotlin(decl.functionSignature.result.type) else {
      printer.print("// Skipped \(decl.displayName): unsupported return type '\(decl.functionSignature.result.type)'")
      return
    }

    // String returns are not supported by FFM generator yet, so skip them in Kotlin too
    if ktReturn == "String" {
      printer.print("// Skipped \(decl.displayName): String return type not supported in FFM mode")
      return
    }

    let paramsString = renderedParams.joined(separator: ", ")
    let throwsComment = decl.isThrowing ? " // throws" : ""

    // Build parameter list for delegation call (just parameter names)
    let paramNames = renderedParams.map { param in
      // Extract parameter name (everything before the colon)
      let parts = param.split(separator: ":")
      return String(parts[0])
    }.joined(separator: ", ")

    // Emit Kotlin top-level function with FFM delegation
    printer.print("fun \(decl.name)(\(paramsString)): \(ktReturn) {\(throwsComment)")

    // Delegate to the generated Java FFM class
    // Java class name is the Swift module name
    if ktReturn == "Unit" {
      printer.print("  \(swiftModuleName).\(decl.name)(\(paramNames))")
    } else {
      printer.print("  return \(swiftModuleName).\(decl.name)(\(paramNames))")
    }

    printer.print("}")
  }
}

