#!/usr/bin/env python3
"""Generate N identical Swift structs + a Kotlin/Native driver that exercises
them all through `Inout<T>`.

Usage: ./gen.py <N>

Every struct is named struct1..structN and has the *same* property names
(`a`, `b`) and method names (`sum`, `scale`) so the generator is stressed on
volume, not on distinct symbols. Each exercise mutates through Inout<T>:
  a=3 -> scale(2) -> 6 -> +1 -> 7 ; b=4 -> scale(2) -> 8 ; sum = 15
so main() asserts the total equals 15 * N.
"""
import sys
import os

N = int(sys.argv[1])
HERE = os.path.dirname(os.path.abspath(__file__))

# ---- Swift source: N identical structs, all in one file ----
swift = ['// AUTO-GENERATED by gen.py — do not edit. N = %d\n' % N,
         'import Swift\n\n']
for i in range(1, N + 1):
    swift.append(f"""public struct struct{i} {{
    public var a: Int
    public var b: Int
    public init(a: Int, b: Int) {{ self.a = a; self.b = b }}
    public func sum() -> Int {{ a + b }}
    public mutating func scale(by factor: Int) {{ a *= factor; b *= factor }}
}}

""")

swift_dir = os.path.join(HERE, "Sources", "StressLib")
os.makedirs(swift_dir, exist_ok=True)
with open(os.path.join(swift_dir, "StressLib.swift"), "w") as f:
    f.write("".join(swift))

# ---- Kotlin driver: one exercise fn per struct + a main that verifies ----
kt = ['// AUTO-GENERATED by gen.py — do not edit. N = %d\n' % N,
      'package com.example.stress\n\n',
      'import org.swift.swiftkit.kn.Inout\n\n']
for i in range(1, N + 1):
    kt.append(f"""private fun exercise{i}(): Long {{
    val s = Inout(struct{i}(3L, 4L))
    s.scale(2L)
    s.a = s.value.a + 1L
    return s.value.sum()
}}

""")

kt.append("fun main() {\n")
kt.append("    var total = 0L\n")
for i in range(1, N + 1):
    kt.append(f"    total += exercise{i}()\n")
kt.append(f"    val expected = 15L * {N}L\n")
kt.append('    if (total != expected) {\n')
kt.append('        error("STRESS FAIL: total=$total expected=$expected")\n')
kt.append("    }\n")
kt.append(f'    println("STRESS OK: N={N} total=$total")\n')
kt.append("}\n")

kt_dir = os.path.join(HERE, "src", "macosArm64Main", "kotlin")
os.makedirs(kt_dir, exist_ok=True)
with open(os.path.join(kt_dir, "Driver.kt"), "w") as f:
    f.write("".join(kt))

print(f"Generated {N} structs -> StressLib.swift and Driver.kt")
