//
//  KotlinNativeSwift2KotlinGenerator+SwiftThunkPrinting.swift
//  swift-java
//
//  Generates the Swift `@_cdecl` thunks consumed by the cinterop header.
//  For most return types the shared `LoweredFunctionSignature.cdeclThunk`
//  produces the correct output.  `[UInt8]` returns use a KN-specific ABI
//  (`uint8_t* thunk(..., ptrdiff_t* result_count)`) because the FFM callback
//  ABI requires `staticCFunction` captures, which Kotlin/Native forbids.
//
import CodePrinting
import SwiftSyntax
import SwiftSyntaxBuilder

extension KotlinNativeSwift2KotlinGenerator {
  /// Write KN-ABI Swift thunks to `<cinteropHeaderDirectory>/<Module>Module+SwiftJava.swift`.
  func writeSwiftThunkSourcesToDisk() throws {
    let filename = "\(swiftModuleName)Module+SwiftJava.swift"
    var printer = CodePrinter()
    try writeSwiftThunkSources(printer: &printer)
    if let url = try printer.writeContents(
      outputDirectory: cinteropHeaderDirectory,
      javaPackagePath: nil,
      filename: filename
    ) {
      log.info("Generated: \(filename) (at \(url.absoluteString))")
    }
  }

  /// Write empty placeholder files for each input `.swift` file so that the
  /// SwiftPM plugin's declared output file list is fully satisfied.
  func writeExpectedEmptySwiftSources() throws {
    guard config.writeEmptyFiles == true else { return }

    var pending: Set<String> = ["Foundation+SwiftJava.swift"]
    for input in translatorInputs {
      let lastComponent = input.path.split(separator: "/").last.map(String.init) ?? input.path
      let basename = lastComponent.hasSuffix(".swift")
        ? String(lastComponent.dropLast(".swift".count))
        : lastComponent
      guard !basename.hasSuffix("+SwiftJava") else { continue }
      pending.insert("\(basename)+SwiftJava.swift")
    }

    for filename in pending {
      var printer = CodePrinter()
      printer.print("// Empty file generated on purpose")
      _ = try printer.writeContents(
        outputDirectory: cinteropHeaderDirectory,
        javaPackagePath: nil,
        filename: filename
      )
    }
  }

  package func writeSwiftThunkSources(printer: inout CodePrinter) throws {
    printer.print("// Generated by jextract-swift (kotlinNative mode)")
    printer.print("")
    printer.print("import SwiftRuntimeFunctions")
    printer.print("")
    symbolTable.printImportedModules(&printer)
    printer.print("")

    for decl in analysis.importedGlobalFuncs {
      guard decl.apiKind == .function,
            decl.hasParent == false,
            decl.isAsync == false else { continue }

      guard let ktReturn = swiftTypeToKotlin(decl.functionSignature.result.type) else { continue }
      guard decl.functionSignature.parameters.allSatisfy({ swiftTypeToKotlin($0.type) != nil })
      else { continue }

      let thunkName = thunkNames.functionThunkName(decl: decl)

      do {
        let lowered = try CdeclLowering(symbolTable: symbolTable)
          .lowerFunctionSignature(decl.functionSignature)

        let thunkDecl: DeclSyntax
        if ktReturn == .array(.uByte) && !decl.isThrowing {
          thunkDecl = arrayReturningThunk(lowered: lowered, decl: decl, thunkName: thunkName)
        } else {
          thunkDecl = DeclSyntax(lowered.cdeclThunk(
            cName: thunkName,
            swiftAPIName: decl.name,
            as: decl.apiKind
          ))
        }

        printer.print(thunkDecl.description)
        printer.print("")
      } catch {
        continue
      }
    }
  }

  private func arrayReturningThunk(
    lowered: LoweredFunctionSignature,
    decl: ImportedFunc,
    thunkName: String
  ) -> DeclSyntax {
    let normalParamDecls = lowered.parameters.flatMap { $0.cdeclParameters }.map(\.description)
    let allParamDecls = (normalParamDecls + ["_ result_count: UnsafeMutablePointer<Int>"]).joined(separator: ", ")

    var thunkFn = try! FunctionDeclSyntax(
      """
      @_cdecl(\(literal: thunkName))
      public func \(raw: thunkName)(\(raw: allParamDecls)) -> UnsafeMutablePointer<UInt8>? {
      }
      """
    )

    var bodyItems: [CodeBlockItemSyntax] = []

    // Reconstruct each Swift argument from its lowered cdecl parameters.
    let paramExprs = lowered.parameters.enumerated().map { idx, param in
      param.conversion.asExprSyntax(
        placeholder: decl.functionSignature.parameters[idx].parameterName ?? "_\(idx)",
        bodyItems: &bodyItems
      )!
    }

    let arguments = paramExprs.enumerated().map { (i, expr) -> String in
      LabeledExprSyntax(
        label: decl.functionSignature.parameters[i].argumentLabel,
        expression: expr
      ).description
    }.joined(separator: ", ")

    bodyItems.append("let _result: [UInt8] = \(raw: decl.name)(\(raw: arguments))")
    bodyItems.append("result_count.pointee = _result.count")
    bodyItems.append("guard !_result.isEmpty else { return nil }")
    bodyItems.append("let _ptr = UnsafeMutablePointer<UInt8>.allocate(capacity: _result.count)")
    bodyItems.append(
      """
      _result.withUnsafeBytes { _buf in
          _ptr.initialize(from: _buf.bindMemory(to: UInt8.self).baseAddress!, count: _result.count)
      }
      """
    )
    bodyItems.append("return _ptr")

    let indented = bodyItems.map { $0.with(\.leadingTrivia, [.newlines(1), .spaces(4)]) }
    thunkFn.body = CodeBlockSyntax(
      statements: CodeBlockItemListSyntax(indented),
      rightBrace: .rightBraceToken(leadingTrivia: .newline)
    )
    return DeclSyntax(thunkFn)
  }

}
