//
//  KotlinNativeSwift2KotlinGenerator.swift
//  swift-java
//
//  Generates Kotlin/Native sources that call the Swift `@_cdecl` C thunks
//  directly via cinterop, with no JVM / Java FFM layer in between.
//
//  This generator emits two artifacts:
//   1. `<Module>.kt`  — Kotlin/Native wrappers that call the cinterop-bound
//      thunk functions (imported via a wildcard import of the cinterop package).
//   2. `<Module>.h`   — a plain-C header declaring the thunks, which the
//      cinterop `.def` consumes. We emit our own clean header rather than the
//      SwiftPM-generated `<Module>-Swift.h` because the latter wraps the
//      thunks in `#pragma clang attribute push(external_source_symbol(
//      language="Swift", ...))`, which makes cinterop treat them as Swift
//      (not C) declarations and skip them.
//
//  Scope (primitive-only, like the `kotlin` JVM mode minus String, which on
//  Kotlin/Native needs explicit memScoped conversion — deferred):
//  Int/Int32/Bool/Double/Void. Everything else is skipped with a comment.
//
import CodePrinting
import SwiftJavaConfigurationShared
import SwiftSyntax
import SwiftSyntaxBuilder
import Foundation

package class KotlinNativeSwift2KotlinGenerator {
  let log: Logger
  let analysis: AnalysisResult
  let swiftModuleName: String
  let kotlinPackage: String
  let kotlinOutputDirectory: String
  let cinteropHeaderDirectory: String

  /// Reuse the same thunk-naming as the FFM generator so the Kotlin calls
  /// resolve to the exact C symbols exported by the Swift `@_cdecl` thunks.
  var thunkNames: ThunkNameRegistry

  /// Plain-C prototypes for the thunks we emit wrappers for, collected while
  /// printing the Kotlin file and re-used when writing the C header so the two
  /// artifacts always stay in sync.
  var cPrototypes: [String] = []

  /// Package that cinterop generates its bindings into (set via the `.def`
  /// `package =` line). Wrappers wildcard-import this package.
  var cinteropPackage: String {
    kotlinPackage.isEmpty ? "cinterop" : "\(kotlinPackage).cinterop"
  }

  package init(config: Configuration, translator: Swift2JavaTranslator,
               kotlinPackage: String, kotlinOutputDirectory: String,
               cinteropHeaderDirectory: String) {
    self.log = Logger(label: "kotlin-native-generator", logLevel: translator.log.logLevel)
    self.analysis = translator.result               // same IR as FFM / Kotlin-JVM generators
    self.swiftModuleName = translator.swiftModuleName
    self.kotlinPackage = kotlinPackage
    self.kotlinOutputDirectory = kotlinOutputDirectory
    self.cinteropHeaderDirectory = cinteropHeaderDirectory
    self.thunkNames = ThunkNameRegistry()
  }

  func generate() throws {
    var printer = CodePrinter()
    try writeExportedKotlinSources(printer: &printer)

    var headerPrinter = CodePrinter()
    try writeCinteropHeader(printer: &headerPrinter)
  }

  // MARK: - Kotlin sources

  package func writeExportedKotlinSources(printer: inout CodePrinter) throws {
    let filename = "\(swiftModuleName).kt"
    printKotlinModuleFile(&printer)
    _ = try printer.writeContents(
      outputDirectory: kotlinOutputDirectory,
      javaPackagePath: kotlinPackage.replacingOccurrences(of: ".", with: "/"),
      filename: filename
    )
  }

  func printKotlinModuleFile(_ printer: inout CodePrinter) {
    printer.print("// Generated by jextract-swift (kotlinNative mode)")
    printer.print("// Swift module: \(swiftModuleName)")
    printer.print("// Calls Swift @_cdecl C thunks directly via Kotlin/Native cinterop\n")
    printer.print("package \(kotlinPackage)\n")
    printer.print("import \(cinteropPackage).*\n")

    for decl in analysis.importedGlobalFuncs {
      printTopLevelKotlinFunction(&printer, decl)
      printer.print("")
    }
  }

  func printTopLevelKotlinFunction(_ printer: inout CodePrinter, _ decl: ImportedFunc) {
    // Only top-level functions: skip members/initializers/accessors/etc.
    guard decl.apiKind == .function else {
      printer.print("// Skipped \(decl.displayName): apiKind=\(decl.apiKind)")
      return
    }
    guard decl.hasParent == false else {
      printer.print("// Skipped \(decl.displayName): not a top-level function (has parent)")
      return
    }
    guard decl.isAsync == false else {
      printer.print("// Skipped \(decl.displayName): async not supported in kotlinNative mode")
      return
    }

    // Render parameters (primitive-only).
    var renderedParams: [String] = []
    var cParamTypes: [String] = []
    var argNames: [String] = []
    renderedParams.reserveCapacity(decl.functionSignature.parameters.count)

    for (i, p) in decl.functionSignature.parameters.enumerated() {
      if swiftTypeToKotlin(p.type) == "String" {
        printer.print("// Skipped \(decl.displayName): String parameter not supported in kotlinNative mode")
        return
      }
      guard let cTy = swiftTypeToC(p.type), let ktTy = swiftTypeToKotlin(p.type) else {
        printer.print("// Skipped \(decl.displayName): unsupported param type '\(p.type)'")
        return
      }
      let name = parameterName(p, at: i)
      renderedParams.append("\(name): \(ktTy)")
      cParamTypes.append(cTy)
      argNames.append(name)
    }

    // Return type (primitive-only).
    if swiftTypeToKotlin(decl.functionSignature.result.type) == "String" {
      printer.print("// Skipped \(decl.displayName): String return type not supported in kotlinNative mode")
      return
    }
    guard
      let cReturn = swiftTypeToC(decl.functionSignature.result.type),
      let ktReturn = swiftTypeToKotlin(decl.functionSignature.result.type)
    else {
      printer.print("// Skipped \(decl.displayName): unsupported return type '\(decl.functionSignature.result.type)'")
      return
    }

    let paramsString = renderedParams.joined(separator: ", ")
    let throwsComment = decl.isThrowing ? " // throws" : ""

    // The C symbol exported by the Swift @_cdecl thunk for this function.
    let thunkName = thunkNames.functionThunkName(decl: decl)
    let argsString = argNames.joined(separator: ", ")

    printer.print("fun \(decl.name)(\(paramsString)): \(ktReturn) {\(throwsComment)")
    if ktReturn == "Unit" {
      printer.print("  \(thunkName)(\(argsString))")
    } else {
      printer.print("  return \(thunkName)(\(argsString))")
    }
    printer.print("}")

    // Record the matching plain-C prototype for the cinterop header.
    let cParams = cParamTypes.isEmpty ? "void" : cParamTypes.joined(separator: ", ")
    cPrototypes.append("\(cReturn) \(thunkName)(\(cParams));")
  }

  // MARK: - cinterop C header

  func writeCinteropHeader(printer: inout CodePrinter) throws {
    let guardName = "\(swiftModuleName.uppercased())_CINTEROP_H"
    printer.print("// Generated by jextract-swift (kotlinNative mode)")
    printer.print("// Plain-C declarations of the Swift @_cdecl thunks for Kotlin/Native cinterop.")
    printer.print("#ifndef \(guardName)")
    printer.print("#define \(guardName)")
    printer.print("")
    for proto in cPrototypes {
      printer.print(proto)
    }
    printer.print("")
    printer.print("#endif")

    _ = try printer.writeContents(
      outputDirectory: cinteropHeaderDirectory,
      javaPackagePath: "",
      filename: "\(swiftModuleName).h"
    )
  }

  // MARK: - Type mapping

  /// Map a Swift known type to its Kotlin equivalent, or `nil` if unsupported.
  func swiftTypeToKotlin(_ t: SwiftType) -> String? {
    if let known = t.asNominalTypeDeclaration?.knownTypeKind {
      switch known {
      case .int: return "Long"
      case .int32: return "Int"
      case .bool: return "Boolean"
      case .double: return "Double"
      case .string: return "String"
      case .void: return "Unit"
      default: break
      }
    }

    switch String(describing: t) {
    case "Int", "Swift.Int": return "Long"
    case "Int32", "Swift.Int32": return "Int"
    case "Bool", "Swift.Bool": return "Boolean"
    case "Double", "Swift.Double": return "Double"
    case "String", "Swift.String": return "String"
    case "Void", "Swift.Void", "()": return "Unit"
    default: return nil
    }
  }

  /// Map a Swift known type to the C type used in the cinterop header, matching
  /// the C ABI of the FFM `@_cdecl` thunks (Swift Int -> NSInteger -> `long`,
  /// Int32 -> `int`, Bool -> `BOOL`/`_Bool`, Double -> `double`). Returns `nil`
  /// for anything not yet supported (including String).
  func swiftTypeToC(_ t: SwiftType) -> String? {
    if let known = t.asNominalTypeDeclaration?.knownTypeKind {
      switch known {
      case .int: return "long"
      case .int32: return "int"
      case .bool: return "_Bool"
      case .double: return "double"
      case .void: return "void"
      default: break
      }
    }

    switch String(describing: t) {
    case "Int", "Swift.Int": return "long"
    case "Int32", "Swift.Int32": return "int"
    case "Bool", "Swift.Bool": return "_Bool"
    case "Double", "Swift.Double": return "double"
    case "Void", "Swift.Void", "()": return "void"
    default: return nil
    }
  }

  /// Resolve a Kotlin-safe parameter name: use the Swift parameter name,
  /// synthesize `p0`/`p1`/... when absent, and backtick-escape keywords.
  func parameterName(_ p: SwiftParameter, at index: Int) -> String {
    var name = (p.parameterName?.trimmingCharacters(in: .whitespacesAndNewlines) ?? "")
    if name.isEmpty || name == "_" {
      name = "p\(index)"
    }
    let kotlinKeywords: Set<String> = [
      "object", "class", "fun", "val", "var", "when", "is", "in",
      "as", "try", "catch", "finally", "null", "true", "false",
    ]
    return kotlinKeywords.contains(name) ? "`\(name)`" : name
  }
}
